### ISSUE TITLE
刷新了固件后，PC进不了LAN端。

### ISSUE THREAD

**Issue by sumingy** [DHDAXCW/DoorNet2#3]
许多DoorNet2固件刷机，用SD启动后，连接PC的LAN不能访问，前面指示灯不亮，PC无法进入；但官方固件启动后就能连接PC。

**Comment by DHDAXCW** [comment]
我的地址是192.168.11.1

**Comment by DHDAXCW** [comment]
是解压刷的嘛？用ext4固件，解压刷上，或者去电报找我

**Comment by DHDAXCW** [comment]
你无法启动，如果是emmc有系统，你直接sd启动后，emmc与sd容易卡rootfs，建议从官方系统执行终端，命令 dd if=/dev/zero of=/dev/mmcblk0 bs=8M count=1 然后reboot，10秒后，拔电，上sd卡，然后上电就能启动了

**Comment by sumingy** [comment]
SD能够启动，状态灯能亮，而LAN灯在连着PC时不会亮，而同样SD刷官方固件，可以启动，LAN灯会亮，PC可进入。

**Comment by DHDAXCW** [comment]
进电报群找我看看
