### ISSUE TITLE
大佬。。PPPOE拨号失败

### ISSUE THREAD

**Issue by Aes64X** [DHDAXCW/DoorNet2#5]
大佬，你在lean那边提交的5.18补丁

808-drv-net-phy-add-JLSemi-jl2xxx-driver

可能有问题，PPPOE拨号失败，我用5.15内核是正常的。

日志如下：

内核日志，频繁提示
[  938.706082] rk_gmac-dwmac fe300000.ethernet eth0: Link is Down
[  938.709329] rk_gmac-dwmac fe300000.ethernet eth0: PHY [stmmac-0:00] driver [JL2101 Gigabit Ethernet] (irq=POLL)
[  938.711567] rk_gmac-dwmac fe300000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
[  938.719984] rk_gmac-dwmac fe300000.ethernet eth0: No Safety Features support found
[  938.720678] rk_gmac-dwmac fe300000.ethernet eth0: PTP not supported by HW
[  938.721287] rk_gmac-dwmac fe300000.ethernet eth0: configuring for phy/rgmii link mode
[  938.723276] rk_gmac-dwmac fe300000.ethernet eth0: Link is Up - 1Gbps/Full - flow control off
[  938.724216] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  938.751422] rk_gmac-dwmac fe300000.ethernet eth0: Link is Down
[  938.755783] rk_gmac-dwmac fe300000.ethernet eth0: PHY [stmmac-0:00] driver [JL2101 Gigabit Ethernet] (irq=POLL)
[  938.758840] rk_gmac-dwmac fe300000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
[  938.768034] rk_gmac-dwmac fe300000.ethernet eth0: No Safety Features support found
[  938.768729] rk_gmac-dwmac fe300000.ethernet eth0: PTP not supported by HW
[  938.769347] rk_gmac-dwmac fe300000.ethernet eth0: configuring for phy/rgmii link mode
[  938.771354] rk_gmac-dwmac fe300000.ethernet eth0: Link is Up - 1Gbps/Full - flow control off
[  938.772246] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready

系统日志，频繁提示
Fri Jan 18 17:06:03 2013 kern.info kernel: [  955.673842] rk_gmac-dwmac fe300000.ethernet eth0: PHY [stmmac-0:00] driver [JL2101 Gigabit Ethernet] (irq=POLL)
Fri Jan 18 17:06:03 2013 kern.info kernel: [  955.676158] rk_gmac-dwmac fe300000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
Fri Jan 18 17:06:03 2013 kern.info kernel: [  955.688071] rk_gmac-dwmac fe300000.ethernet eth0: No Safety Features support found
Fri Jan 18 17:06:03 2013 kern.info kernel: [  955.688757] rk_gmac-dwmac fe300000.ethernet eth0: PTP not supported by HW
Fri Jan 18 17:06:03 2013 kern.info kernel: [  955.689367] rk_gmac-dwmac fe300000.ethernet eth0: configuring for phy/rgmii link mode
Fri Jan 18 17:06:03 2013 daemon.notice netifd: Interface 'wan' is enabled
Fri Jan 18 17:06:03 2013 daemon.notice netifd: Interface 'wan' is setting up now
Fri Jan 18 17:06:03 2013 kern.info kernel: [  955.695264] rk_gmac-dwmac fe300000.ethernet eth0: Link is Up - 1Gbps/Full - flow control off
Fri Jan 18 17:06:03 2013 kern.info kernel: [  955.696202] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Fri Jan 18 17:06:03 2013 daemon.err insmod: module is already loaded - slhc
Fri Jan 18 17:06:03 2013 daemon.err insmod: module is already loaded - ppp_generic
Fri Jan 18 17:06:03 2013 daemon.err insmod: module is already loaded - pppox
Fri Jan 18 17:06:03 2013 daemon.err insmod: module is already loaded - pppoe
Fri Jan 18 17:06:03 2013 daemon.notice netifd: wan (2017): uci: Entry not found
Fri Jan 18 17:06:03 2013 daemon.notice netifd: wan (2017): sh: out of range
Fri Jan 18 17:06:03 2013 daemon.info pppd[2049]: Plugin pppoe.so loaded.
Fri Jan 18 17:06:03 2013 daemon.info pppd[2049]: PPPoE plugin from pppd 2.4.9
Fri Jan 18 17:06:03 2013 daemon.notice pppd[2049]: pppd 2.4.9 started by vServer, uid 0
Fri Jan 18 17:06:18 2013 daemon.warn pppd[2049]: Timeout waiting for PADO packets
Fri Jan 18 17:06:18 2013 daemon.err pppd[2049]: Unable to complete PPPoE Discovery
Fri Jan 18 17:06:18 2013 daemon.info pppd[2049]: Exit.

**Comment by Aes64X** [comment]
> 看样子没啥问题

呃。。。目前是5.15没啥事儿，我找个时间再复现一下，也就换个TF卡就行，先关闭了。

**Comment by Aes64X** [comment]
> 看样子没啥问题
[内核日志.txt](https://github.com/DHDAXCW/DoorNet2/files/9125144/default.txt)
[系统日志.txt](https://github.com/DHDAXCW/DoorNet2/files/9125145/default.txt)

**Comment by Aes64X** [comment]
> 看样子没啥问题

保存了完整的启动日志

**Comment by DHDAXCW** [comment]
看起来是上游少了一个补丁引起的

**Comment by DHDAXCW** [comment]
--- a/drivers/net/ethernet/stmicro/stmmac/stmmac_mdio.c
+++ b/drivers/net/ethernet/stmicro/stmmac/stmmac_mdio.c
@@ -498,6 +498,11 @@ int stmmac_mdio_register(struct net_devi
 	if (priv->plat->has_xgmac)
 		stmmac_xgmac2_mdio_read(new_bus, 0, MII_ADDR_C45);
 
+		stmmac_mdio_write(new_bus,0,31,2627);
+		stmmac_mdio_write(new_bus,0,25,0x1801);
+		stmmac_mdio_write(new_bus,0,31,0);
+		stmmac_mdio_write(new_bus,0,0,0x8000);
+
 	if (priv->plat->phy_node || mdio_node)
 		goto bus_register_done;
 
--- a/drivers/net/ethernet/stmicro/stmmac/stmmac_main.c
+++ b/drivers/net/ethernet/stmicro/stmmac/stmmac_main.c
@@ -2907,6 +2907,8 @@ static int stmmac_init_dma_engine(struct
 	if (priv->extend_desc && (priv->mode == STMMAC_RING_MODE))
 		atds = 1;
 
+	msleep(1500);
+
 	ret = stmmac_reset(priv, priv->ioaddr);
 	if (ret) {
 		dev_err(priv->device, "Failed to reset the dma\n");

**Comment by Aes64X** [comment]
> 少了这个补丁
> 
> ```
> +++ b/drivers/net/ethernet/stmicro/stmmac/stmmac_mdio.c
> @@ -498,6 +498,11 @@ int stmmac_mdio_register(struct net_devi
>  	if (priv->plat->has_xgmac)
>  		stmmac_xgmac2_mdio_read(new_bus, 0, MII_ADDR_C45);
>  
> +		stmmac_mdio_write(new_bus,0,31,2627);
> +		stmmac_mdio_write(new_bus,0,25,0x1801);
> +		stmmac_mdio_write(new_bus,0,31,0);
> +		stmmac_mdio_write(new_bus,0,0,0x8000);
> +
>  	if (priv->plat->phy_node || mdio_node)
>  		goto bus_register_done;
>  
> --- a/drivers/net/ethernet/stmicro/stmmac/stmmac_main.c
> +++ b/drivers/net/ethernet/stmicro/stmmac/stmmac_main.c
> @@ -2907,6 +2907,8 @@ static int stmmac_init_dma_engine(struct
>  	if (priv->extend_desc && (priv->mode == STMMAC_RING_MODE))
>  		atds = 1;
>  
> +	msleep(1500);
> +
>  	ret = stmmac_reset(priv, priv->ioaddr);
>  	if (ret) {
>  		dev_err(priv->device, "Failed to reset the dma\n");
> ```

稍后我将测试一下

**Comment by DHDAXCW** [comment]
你把这个复制到新建文件，名为 9999-fix-stmmac_mdio.patch，然后丢/target/linux/rockchip/patches-5.18/目录下，编译好了再试试

**Comment by Aes64X** [comment]
> 

好的

**Comment by Aes64X** [comment]
> 你把这个复制到新建文件，名为 9999-fix-stmmac_mdio.patch，然后丢/target/linux/rockchip/patches-5.18/目录下，编译好了再试试

正在执行，大约一小时后我将反馈。

**Comment by DHDAXCW** [comment]
你直接给全核心就好了，很快的

**Comment by Aes64X** [comment]
> 你直接给全核心就好了，很快的

12核心在跑，到target/linux compile了

**Comment by DHDAXCW** [comment]
target/linux编译kernel  12核 4.9GHz需要4分种~

**Comment by Aes64X** [comment]
> target/linux编译
[内核日志.txt](https://github.com/DHDAXCW/DoorNet2/files/9125234/default.txt)
[系统日志.txt](https://github.com/DHDAXCW/DoorNet2/files/9125235/default.txt)
kernel 12核 4.9GHz需要4分种~

这是新的启动日志，已经可以正常拨号了。

**Comment by DHDAXCW** [comment]
![image](https://user-images.githubusercontent.com/74764072/179341579-f2100dd3-f187-4e0e-bc27-969193f57f9b.png)
